name: ALEEnvironment
args:
  rom: space_invaders
  display_screen: False
  play_sound: False
  repeat_action: 4
  # This number of frames are played with action=0 at each reset.
  random_start: 30
  # Affects if loss of life is considered as terminal condition or not
  mode: train
  # Get screen in grayscale NumPy array with shape (height, width) or (color, height, width)
  grayscale: True
