name: ALEEnvironment
args:
  rom: breakout
  display_screen: False
  sound: False
  frame_skip: 4
  color_averaging: False
  random_start: 30
  # This number of frames are played with action=0 at each reset.